name: Build

on: [push, pull_request]

env:
  DOCKER_FLAGS: ""

jobs:
  gcc_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with gcc
      run: make docker_test_gcc
  clang_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with clang
      run: make docker_test_clang
  valgrind_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with valgrind
      run: make docker_test_valgrind
  #release_build_test:
    #runs-on: ubuntu-20.04
    #steps:
    #- uses: actions/checkout@v1
    #- name: checkout submodules
      #run: git submodule update --init --recursive
    #- name: test release build
      #run: make docker_test_release
