name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_FLAGS: ""

jobs:
  gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with gcc
      run: make docker_test_gcc
  clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with clang
      run: make docker_test_clang
  release_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test release build
      run: make docker_test_release
  ruby3:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with Ruby 3.0
      run: make docker_test_gcc
