name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
      env:
        DOCKER_FLAGS: ""
    - name: test with gcc
      run: make docker_test_gcc
      env:
        DOCKER_FLAGS: ""
    - name: test with clang
      run: make docker_test_clang
      env:
        DOCKER_FLAGS: ""
    - name: test with valgrind
      run: make docker_test_valgrind
      env:
        DOCKER_FLAGS: ""
    - name: test release build
      run: make docker_test_release
      env:
        DOCKER_FLAGS: ""
